### ISSUE TITLE
Constructors for derived classes must contain a 'super' call

### ISSUE THREAD

**Issue by Benjamindudok** [jgveire/VanType#3]
Since the latest version, model generation has been enhanced with a constructor for each model. But when a model extends another model. The base constructor isn't called and the typescript compiler doesn't accept this.

```
export class Model extends BaseModel
{
    constructor(init?: Partial<IAssessorResult>) {
        super(); // this must be added when the model is extending another model
        Object.assign(this, init);
    }
}
```

**Comment by jgveire** [comment]
Fixed the issue in version 3.2.1
